name: Build and deploy

on:
  push:
    branches: [ main ]
    
  # Run workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          VUE_APP_API_KEY: ${{ secrets.VUE_APP_API_KEY }}
          VUE_APP_AUTH_DOMAIN: ${{ secrets.VUE_APP_AUTH_DOMAIN }}
          VUE_APP_DATABASE_URL: ${{ secrets.VUE_APP_DATABASE_URL }}
          VUE_APP_PROJECT_ID: ${{ secrets.VUE_APP_PROJECT_ID }}
          VUE_APP_STORAGE_BUCKET: ${{ secrets.VUE_APP_STORAGE_BUCKET }}
          VUE_APP_MESSAGING_SENDER_ID: ${{ secrets.VUE_APP_MESSAGING_SENDER_ID }}
          VUE_APP_APP_ID: ${{ secrets.VUE_APP_APP_ID }}
          VUE_APP_MEASUREMENT_ID: ${{ secrets.VUE_APP_MEASUREMENT_ID }}
          VUE_APP_SHORTER_URL: ${{ secrets.VUE_APP_SHORTER_URL }}
          VUE_APP_STRIPE_PUBLISHABLE_KEY: ${{ secrets.VUE_APP_STRIPE_PUBLISHABLE_KEY }}
          VUE_APP_STRIPE_MONTHLY_PRICE_ID: ${{ secrets.VUE_APP_STRIPE_MONTHLY_PRICE_ID }}
          VUE_APP_STRIPE_YEARLY_PRICE_ID: ${{ secrets.VUE_APP_STRIPE_YEARLY_PRICE_ID }}
          VUE_APP_VERSION: ${{ github.run_id }}
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P production --only hosting
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
